# Generated by Django 5.0 on 2023-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.TextField(default='mian/images/retaurants/image_1'),
            preserve_default=False,
        ),
    ]
